@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bytelaw.bytesstructures.feature;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;