@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bytelaw.bytesstructures.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;