@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bytelaw.bytesstructures.feature.structure;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;