@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bytelaw.bytesstructures.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;