@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.bytelaw.bytesstructures.world;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;